name: cinema

volumes:
  postgresql: {}

services:

  reverse-proxy:
    image: traefik:v3.4
    volumes:
      - ./traefik:/etc/traefik:ro,Z
    ports:
      - 8443:8443
    environment:
      TZ: Europe/Paris

  whoami:
    image: traefik/whoami
    depends_on:
      - reverse-proxy
    environment:
      WHOAMI_PORT_NUMBER: 8000
      WHOAMI_NAME: cinema

  postgresql:
    build:
      context: ./postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cinema}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-cinema}", "-d", "${POSTGRES_USER:-cinema}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  toxiproxy:
    image: shopify/toxiproxy
    command: ["-host=0.0.0.0"]

  toxiproxy_init:
    image: curlimages/curl
    depends_on:
      - toxiproxy
    entrypoint: [ "sh", "-c", "sleep 2 && ./toxiproxy-init.sh" ]
    volumes:
      - ./toxiproxy/init.sh:/toxiproxy-init.sh:ro,Z
    working_dir: /

  postgrest:
    image: postgrest/postgrest:v13.0.0
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://postgrest:9012@postgresql/cinema
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: role_web
      PGRST_SERVER_PORT: 8001

  postgraphile:
    build:
      context: ./postgraphile
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      PGHOST: postgresql
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER:-cinema}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${POSTGRES_USER:-cinema}

  phpcrudapi:
    build:
      context: ./phpcrudapi
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      SERVER_NAME: :8003
      PHP_CRUD_API_DRIVER: pgsql
      PHP_CRUD_API_ADDRESS: postgresql
      PHP_CRUD_API_PORT: 5432
      PHP_CRUD_API_DATABASE: ${POSTGRES_USER:-cinema}
      PHP_CRUD_API_USERNAME: ${POSTGRES_USER:-cinema}
      PHP_CRUD_API_PASSWORD: ${PGPASSWORD}
      PHP_CRUD_API_DEBUG: 1

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    environment:
      IMGPROXY_BIND: :8004
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /images
      IMGPROXY_USE_ETAG: 1
      IMGPROXY_AUTO_WEBP: 1
      IMGPROXY_AUTO_AVIF: 1
      IMGPROXY_AUTO_JXL: 1
      IMGPROXY_ALLOW_ORIGIN: "*"
    volumes:
      - ../images:/images:ro,Z

  pgadmin:
    image: dpage/pgadmin4:9.4
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: emmanuel.medina@univ-lorraine.fr
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
      PGADMIN_LISTEN_PORT: 8006

  onsenui:
    image: caddy
    volumes:
      - ../onsenui:/srv:Z
    command: ["caddy", "file-server", "--listen", ":8005", "--root", "/srv"]
