###
POST https://graphql.info.localhost:8443/graphql
Content-Type: application/graphql

query Personnes {
  allPersonnes(first: 10) {
    nodes {
      nom
      prenom
      artiste
    }
  }
}

### Acteurs
POST https://graphql.info.localhost:8443/graphql
Content-Type: application/graphql

query Acteurs {
  allActeurs {
    nodes {
      personneId
      nom
      age
      naissance
      deces
      nationalite
      nbFilm
    }
  }
}
