http:
  routers:
    whoami:
      rule: "Host(`whoami.localhost`)"
      service: whoami
      entryPoints:
        - web
    rest:
      rule: "Host(`rest.localhost`)"
      service: rest
      tls: true
      entryPoints:
        - websecure

  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami"

    rest:
      loadBalancer:
        servers:
          - url: "http://postgrest:8000"
