/*
alter default privileges
  for role postgres
  in schema cinema
  grant insert, select, update, delete on tables to iutsd;
*/
-- Personnes

create table personnes (
  personne_id int not null,
  nom text,
  prenom text,
  naissance date,
  deces date,
  nationalite text,
  artiste text,
  popularite decimal default 0
);

alter table personnes
  add constraint personne_naissance
  check (naissance > '1730-01-01') not valid;

alter table personnes
  add constraint personne_deces
  check (deces > naissance) not valid;

alter table personnes
  add constraint personne_nationalite
  check (char_length(nationalite) = 2) not valid;

create unique index personnes_unique
  on personnes using btree (nom, prenom);

alter table personnes
  add constraint personnes_unique unique
  using index personnes_unique;

-- Clé primaire auto incrément

alter table personnes
  alter column personne_id
  add generated by default as identity;

create unique index personnes_pk
  on personnes
  using btree (personne_id);

alter table personnes
  add primary key using index personnes_pk;

--

alter table personnes
  add column created_at timestamp with time zone default now(),
  add column updated_at timestamp with time zone;

-- Sociétés

create table societes (
  societe_id int not null,
  societe text not null,
  uei text
);

comment on column societes.uei is 'Unique Entity ID';

alter table societes
  alter column societe_id
  add generated by default as identity;

alter table societes
  add primary key (societe_id);

-- A transformer en table

create type role as enum (
  'acteur',
  'voix',
  'réalisateur',
  'scénariste',
  'musique',
  'roman'
);
