create table series (
  serie_id integer not null,
  serie text not null
);

alter table series
  alter column serie_id
  add generated by default as identity;

alter table series
  add primary key (serie_id);


create table films (
  film_id int not null,
  titre text not null,
  titre_original text,
  annee integer,
  sortie date,
  duree integer,
  serie_id integer,
  slogan text,
  pays text[]
);

alter table films
  alter column film_id
  add generated by default as identity;

alter table films
  add primary key (film_id);


alter table films
  add column created_at timestamp with time zone default now(),
  add column updated_at timestamp with time zone;

alter table films
  add foreign key (serie_id)
    references series match simple
    on update no action
    on delete no action
    not valid;


create table motscles (
  motcle_id integer not null,
  motcle text not null
);

alter table motscles
  add primary key (motcle_id);

create table films_motscles (
  film_id int not null,
  motcle_id integer not null
);

-- films_motscles -> films

create unique index film_motscles_pkey
  on films_motscles
  using btree (film_id, motcle_id);

alter table films_motscles
  add primary key
  using index film_motscles_pkey;

create index film_motscles_films
  on films_motscles
  using btree (film_id);

-- films_motscles -> motscles

create index film_motscles_motscles
  on films_motscles
  using btree (motcle_id);

alter table films_motscles
  add foreign key (film_id)
  references films(film_id)
  on delete cascade;


alter table films_motscles
  add foreign key (motcle_id)
  references motscles(motcle_id)
  on delete cascade;

-- Genres

create table genres (
  genre_id integer not null,
  genre text not null
);

-- Clé primaire auto incrément

alter table genres
  alter column genre_id
  add generated by default as identity;

create unique index genres_pk
  on genres
  using btree (genre_id);

alter table genres
  add primary key using index genres_pk;
