create table if not exists salles (
  salle_id integer not null,
  etablissement_id integer not null,
  salle text not null,
  sieges integer not null
);

alter table salles
  add primary key (salle_id);

alter table salles
  add foreign key (etablissement_id) references etablissements
  on delete cascade;


-- seances

create table if not exists seances (
  seance_id int not null,
  film_id int not null,
  salle_id int not null,
  seance date not null
);


alter table seances
  alter column seance_id
  add generated by default as identity;

create index on seances
  using btree (film_id);

create index on seances
  using btree (salle_id);

alter table seances
  add primary key (seance_id);

alter table seances
add foreign key (film_id) references films
  on delete cascade;

alter table seances
  add foreign key (salle_id) references salles;
