create table quizzes (
  quiz_id integer not null,
  quiz text not null,
  questions json not null
);

alter table quizzes
  alter column quiz_id
  add generated by default as identity;

alter table quizzes
  add primary key (quiz_id);
